notifications:
  email: true

sudo: false

language: c

matrix:
  fast_finish: true
  include:
    - name: 8-2018-q4
      env: GCC_URL=https://developer.arm.com/-/media/Files/downloads/gnu-rm/8-2018q4/gcc-arm-none-eabi-8-2018-q4-major-linux.tar.bz2?revision=d830f9dd-cd4f-406d-8672-cca9210dd220?product=GNU%20Arm%20Embedded%20Toolchain,64-bit,,Linux,8-2018-q4-major

addons:
  apt:
    packages:
    - libc6-i386 





install:
  - env
  - pushd .
  - cd ~ 
  - mkdir arm-gcc-toolchain
  - wget -O $HOME/arm-gcc-toolchain/gcc.tar.bz2 $GCC_URL
  - cd arm-gcc-toolchain
  - tar -jxf gcc.tar.bz2 --strip=1
  - cd $HOME
  - svn checkout https://svn.code.sf.net/p/freertos/code/trunk freertos-code
  - popd
  - export PATH=$HOME/arm-gcc-toolchain/bin:$PATH
  - export FREERTOS_ROOT=$HOME/freertos-code/FreeRTOS/Source
  - export FREERTOS_PLUS_ROOT=$HOME/freertos-code/FreeRTOS-Plus/Source

before_script:
  - arm-none-eabi-gcc --version

script:
  - make VERBOSE=1
