/*
 * printf_config.h
 *
 *  Created on: Jan 2025
 *      Author: pw94
 */

#ifndef PROD_TEST_PRINTF_CONFIG_H_
#define PROD_TEST_PRINTF_CONFIG_H_

#define PRINTF_DISABLE_SUPPORT_EXPONENTIAL
#define PRINTF_DISABLE_SUPPORT_LONG_LONG
#define PRINTF_DISABLE_SUPPORT_PTRDIFF_T
#endif /* PROD_TEST_PRINTF_CONFIG_H_ */
