/*
 * printf_config.h
 *
 *  Created on: Jun 1, 2021
 *      Author: pw94
 */

#ifndef COMMON_PRINTF_CONFIG_H_
#define COMMON_PRINTF_CONFIG_H_

#define PRINTF_DISABLE_SUPPORT_FLOAT
#define PRINTF_DISABLE_SUPPORT_EXPONENTIAL
#define PRINTF_DISABLE_SUPPORT_LONG_LONG
#define PRINTF_DISABLE_SUPPORT_PTRDIFF_T
#endif /* COMMON_PRINTF_CONFIG_H_ */
