name: C/C++ CI

on:
  push:
    branches: [ master pw-patch-1 ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Code checkout
      uses: actions/checkout@v2
    - name: Check cache for Embedded Arm Toolchain arm-none-eabi-gcc
      id:   cache-toolchain
      uses: actions/cache@v2
      env:
        cache-name: cache-toolchain-9-2020-q2
      with:
        path: ${{ runner.temp }}/arm-none-eabi
        key:  ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}

    - name: Install Embedded Arm Toolchain arm-none-eabi-gcc
      if:   steps.cache-toolchain.outputs.cache-hit != 'true'  # Install toolchain if not found in cache
      uses: fiam/arm-none-eabi-gcc@v1.0.4
      with:
      # GNU Embedded Toolchain for Arm release name, in the V-YYYY-qZ format (e.g. "9-2019-q4")
        release: 9-2020-q2
        # Directory to unpack GCC to. Defaults to a temporary directory.
        directory: ${{ runner.temp }}/arm-none-eabi
#    #- name: FreeRTOS cache check 
#    #  uses: actions/cache@v2
#    #  env:
#    #   cache-name: cache-freertos-ltos-20201201
#    #  with: 
    - name: FreeRTOS download
      run: |
         mkdir freertos-lts
         cd freertos-lts
         curl -L -o freertos_code.zip https://github.com/FreeRTOS/FreeRTOS-LTS/releases/download/202012.01-LTS/FreeRTOSv202012.01-LTS.zip
         unzip -q   freertos_code.zip  -d freertos-code
         echo "FREERTOS_ROOT=`pwd`/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Kernel" >> $GITHUB_ENV
         echo $FREERTOS_ROOT
         ls
         pwd
    - name: test
      run: |
        echo $FREERTOS_ROOT
        which arm-none-eabi-gcc
        arm-none-eabi-gcc --version 
#    - name: CLANG compiler setup
#      uses: egor-tensin/setup-clang@v1
#    - name: make with CLANG
#      run: make COMPILER=clang
    - name: make with GCC
      run: make -k  
