name: C/C++ CI

on:
  push:
    branches: [ master pw-patch-1 ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Code checkout
      uses: actions/checkout@v2
    - name: Check cache for Embedded Arm Toolchain arm-none-eabi-gcc
      id:   cache-toolchain
      uses: actions/cache@v2
      env:
        cache-name: cache-toolchain-9-2020-q2
      with:
        path: ${{ runner.temp }}/arm-none-eabi
        key:  ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}

    - name: Install Embedded Arm Toolchain arm-none-eabi-gcc
      if:   steps.cache-toolchain.outputs.cache-hit != 'true'  # Install toolchain if not found in cache
      run: |
        curl -L -o $HOME/arm-gcc-toolchain/gcc.tar.bz2 https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2019q4/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2?revision=108bd959-44bd-4619-9c19-26187abf5225%26la=en%26hash=E788CE92E5DFD64B2A8C246BBA91A249CB8E2D2D
        cd arm-gcc-toolchain
        tar -jxf gcc.tar.bz2 --strip=1
        cd $HOME
      
#    #- name: FreeRTOS cache check 
#    #  uses: actions/cache@v2
#    #  env:
#    #   cache-name: cache-freertos-ltos-20201201
#    #  with: 
    - name: Check cache for FreeRTOS
      id:   cache-freertos
      uses: actions/cache@v2
      env:
        cache-name: cache-toolchain-ltos-20201201
      with:
        path: ${{ runner.temp }}/freertos-lts
        key:  ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: FreeRTOS download
      run: |
         cd 
         mkdir freertos-lts
         cd freertos-lts
         curl -L -o freertos_code.zip https://github.com/FreeRTOS/FreeRTOS-LTS/releases/download/202012.01-LTS/FreeRTOSv202012.01-LTS.zip
         unzip -q freertos_code.zip -d freertos-code
         echo "FREERTOS_ROOT=`pwd`/FreeRTOS-LTS/FreeRTOS/FreeRTOS-Kernel" >> $GITHUB_ENV
         echo $FREERTOS_ROOT
         pwd
    - name: test
      run: |
        echo $FREERTOS_ROOT
#    - name: CLANG compiler setup
#      uses: egor-tensin/setup-clang@v1
#    - name: make with CLANG
#      run: make COMPILER=clang
    - name: make with GCC
      run: |
        export PATH=$HOME/arm-gcc-toolchain/bin:$PATH
        make -k  
