name: Format and Commit

on: workflow_dispatch


jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
    - name: Code checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v35
      with:
        base_sha: ${{ github.event.pull_request.base.sha }}
        files_ignore: |
          **/*.yml
          .clang*
          .git*
          **/*.sh
          **/*.def
          **/Makefile
          makedefs
    - name: Format changed files
      uses: DoozyX/clang-format-lint-action@v0.14
      if: steps.changed-files.outputs.any_changed == 'true'
      with:
        source: ${{ steps.changed-files.outputs.all_changed_files }}
        extensions: 'h,c'
        clangFormatVersion: 11
        inplace: true
        style: file
    - name: Commit clang-formatted files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply clang-format changes
