name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Set to true to skip actual release creation"
        required: false
        default: "false"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Install Embedded Arm Toolchain arm-none-eabi-gcc
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: "13.2.Rel1" # The arm-none-eabi-gcc release to use.

      - name: Prepare workspace
        run: |
          mkdir build
          cp -r * build/
      # Upload the prepared workspace as an artifact
      - name: Upload workspace
        uses: actions/upload-artifact@v4
        with:
          name: workspace
          path: build/

  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        revision: ["REV1", "REV2", "REV3"]
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v3
        with:
          name: workspace

      - name: Build for ${{ matrix.revision }}
        run: |
          rev="${{ matrix.revision }}"
          rev_lower=$(echo "$rev" | tr '[:upper:]' '[:lower:]')
          cd build
          make clean ${{ matrix.revision }}=1
          make -k NO_ECN001=1 ${{ matrix.revision }}=1
          cp projects/cm_mcu/gcc/cm_mcu.bin cm_mcu_noecn001_${rev_lower}.bin
          cp projects/cm_mcu/gcc/cm_mcu.axf cm_mcu_noecn001_${rev_lower}.axf
          make clean ${{ matrix.revision }}=1
          make -k ${{ matrix.revision }}=1
          mkdir -p ${{ github.ref_name }}/${{ matrix.revision }}
          cp projects/cm_mcu/gcc/cm_mcu.bin ${{ github.ref_name }}/${{ matrix.revision }}/cm_mcu_${rev_lower}.bin
          cp projects/cm_mcu/gcc/cm_mcu.axf ${{ github.ref_name }}/${{ matrix.revision }}/cm_mcu_${rev_lower}.axf
          cp projects/boot_loader/gcc/bl_main.bin ${{ github.ref_name }}/${{ matrix.revision }}/bl_main_${rev_lower}.bin
          cp projects/boot_loader/gcc/bl_main.axf ${{ github.ref_name }}/${{ matrix.revision }}/bl_main_${rev_lower}.axf
          make ${{ matrix.revision }}=1 release
          mv PL_MEM_CM_${rev_lower}.xml ${{ github.ref_name }}/${{ matrix.revision }}
          mv CornellCM_MCU.tar.gz ${{ github.ref_name }}/${{ matrix.revision }}
          tar zcvpf cm_mcu_${rev_lower}_${{ github.ref_name }}.tar.gz ${{ github.ref_name }}/${{ matrix.revision }}

      - name: Upload build artifacts for ${{ matrix.revision }}
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.revision }}
          path: ${{ github.ref_name }}/${{ matrix.revision }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts/

      - name: Test
        run: |
          pwd
          ls -R artifacts/
          find artifacts/ -type f -name '*.axf' -print

      - name: Dry run release (simulation)
        if: ${{ inputs.dry_run == 'true' }}
        run: |
          echo "Dry run enabled. The following artifacts would be released:"
          find artifacts/ -type f -print

      - name: Create GitHub Release
        if: ${{ inputs.dry_run != 'true' }}
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            artifacts/**
            *.tar.gz
